/**
 * Plain text export — zero dependencies.
 * Generates a readable plain-text audit report.
 */
import { CHECKLIST_LABELS } from '../../constants/checklistLabels';

export const exportTXT = (report, url) => {
  if (!report) return;

  const divider = '═'.repeat(60);
  const subDivider = '─'.repeat(40);
  let txt = '';

  txt += `${divider}\n`;
  txt += `  GROWAGENT CRO AUDIT REPORT\n`;
  txt += `${divider}\n\n`;
  txt += `  Website:  ${url}\n`;
  txt += `  Date:     ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}\n`;
  txt += `  Score:    ${report.overall_score}/100\n\n`;
  txt += `${divider}\n\n`;

  // Summary
  txt += `EXECUTIVE SUMMARY\n${subDivider}\n${report.summary || 'N/A'}\n\n`;

  // Strengths
  if (report.strengths?.length > 0) {
    txt += `WHAT'S WORKING\n${subDivider}\n`;
    report.strengths.forEach(s => { txt += `  + ${s}\n`; });
    txt += '\n';
  }

  // Quick Wins
  if (report.quick_wins?.length > 0) {
    txt += `QUICK WINS\n${subDivider}\n`;
    report.quick_wins.forEach(q => { txt += `  > ${q}\n`; });
    txt += '\n';
  }

  // Checklist Scores
  if (report.checklist_scores && Object.keys(report.checklist_scores).length > 0) {
    txt += `CRO CHECKLIST SCORES\n${subDivider}\n`;
    Object.entries(report.checklist_scores).forEach(([key, score]) => {
      const label = (CHECKLIST_LABELS[key] || key.replace(/_/g, ' ')).padEnd(22);
      const bar = '█'.repeat(Math.round(score / 5)) + '░'.repeat(20 - Math.round(score / 5));
      txt += `  ${label} ${bar}  ${score}/100\n`;
    });
    txt += '\n';
  }

  // Critical Failures
  if (report.checklist_flags?.length > 0) {
    txt += `CRITICAL FAILURES\n${subDivider}\n`;
    report.checklist_flags.forEach(f => { txt += `  X ${f}\n`; });
    txt += '\n';
  }

  // Competitor Analysis
  if (report.competitor_analysis?.comparisons?.length > 0) {
    txt += `COMPETITIVE INTELLIGENCE\n${subDivider}\n`;
    txt += `${report.competitor_analysis.overview}\n\n`;
    report.competitor_analysis.comparisons.forEach(c => {
      txt += `  vs. ${c.competitor}\n`;
      txt += `    Difference: ${c.difference}\n`;
      txt += `    Advantage:  ${c.advantage}\n`;
      if (c.steal_worthy?.length > 0) {
        txt += `    Steal-worthy:\n`;
        c.steal_worthy.forEach(s => { txt += `      - ${s}\n`; });
      }
      txt += '\n';
    });
  }

  // Page Scores
  if (report.page_scores?.length > 0) {
    txt += `SITE-WIDE PAGE SCORES\n${subDivider}\n`;
    report.page_scores.forEach(p => {
      txt += `  ${p.page_type || 'Page'} (${p.url}): ${p.overall_score}/100\n`;
      (p.top_issues || []).forEach(issue => { txt += `    - ${issue}\n`; });
    });
    txt += '\n';
  }

  // Recommendations
  txt += `PRIORITIZED RECOMMENDATIONS\n${subDivider}\n`;
  (report.recommendations || []).forEach((r, i) => {
    txt += `\n  #${i + 1} [${(r.priority || 'Medium').toUpperCase()}] ${r.category || 'General'}\n`;
    txt += `  Issue:          ${r.issue || 'N/A'}\n`;
    txt += `  Recommendation: ${r.recommendation || 'N/A'}\n`;
    txt += `  Impact:         ${r.expected_impact || 'N/A'}\n`;
    txt += `  Implementation: ${r.implementation || 'N/A'}\n`;
    if (r.checklist_ref) txt += `  Checklist:      ${r.checklist_ref}\n`;
  });

  txt += `\n${divider}\n`;
  txt += `Generated by GROWAGENT | AI-Powered CRO Analysis | growme.ca\n`;

  const blob = new Blob([txt], { type: 'text/plain' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `GrowAgent_${new URL(url).hostname}_Report.txt`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 1000);
};
